# Dependabot template

version: 2
updates:

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "git submod"
    labels:
      - "git submods"
      - "updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "git action"
    labels:
      - "git actions"
      - "updates"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip"
    labels:
      - "pip"
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "cargo"
    labels:
      - "cargo"
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "golang"
    labels:
      - "golang"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker composer"
    labels:
      - "composer"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "bundler"
    labels:
      - "bundler"
      - "dependencies"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gradle"
    labels:
      - "gradle"
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ".NET"
    labels:
      - ".NET"
      - "dependencies"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dart"
    labels:
      - "dart"
      - "dependencies"
